---
# tasks file for prometheus-node

- name: prometheus node | create directories
  become: true
  ansible.builtin.file:
    path: /opt/prometheus
    state: directory
    mode: 0755

- name: prometheus node | download node-exporter
  become: true
  ansible.builtin.get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/\
      v{{ prometheus_node_version }}/node_exporter-{{ prometheus_node_version
      }}.linux-amd64.tar.gz"
    checksum: "sha256:{{ prometheus_node_sha256 }}"
    dest: "/opt/prometheus/\
      node_exporter-{{ prometheus_node_version }}.linux-amd64.tar.gz"
    force: false

- name: prometheus node | install node-exporter
  become: true
  ansible.builtin.unarchive:
    src: "/opt/prometheus/\
      node_exporter-{{ prometheus_node_version }}.linux-amd64.tar.gz"
    dest: /opt/prometheus
    group: root
    owner: root
    remote_src: true

- name: prometheus node | symlink node-exporter
  become: true
  ansible.builtin.file:
    src: "/opt/prometheus/\
      node_exporter-{{ prometheus_node_version }}.linux-amd64"
    path: /opt/prometheus/node_exporter
    force: true
    state: link
  notify:
    - reload systemd
    - restart prometheus-node-exporter

- name: prometheus node | systemd service
  become: true
  ansible.builtin.template:
    dest: "/etc/systemd/system/prometheus-node-exporter.service"
    force: true
    src: "systemd-system-prometheus-node-exporter-service.j2"
    mode: 0644
  notify:
    - reload systemd
    - restart prometheus-node-exporter

# Flush handlers to ensure systemd is reloaded
- name: prometheus node | flush systemd handlers
  ansible.builtin.meta: flush_handlers

- name: prometheus node | enable and start systemd service
  become: true
  ansible.builtin.service:
    enabled: true
    name: prometheus-node-exporter.service
    state: started
